import { Inter } from 'next/font/google'
import './globals.css'
<<<<<<< HEAD
import Navbar from '@/components/Navbar'
=======
>>>>>>> af25d0a8041f5aae49e1453e07b82dd31a164558

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
<<<<<<< HEAD
  title: 'AnimeList',
  description: 'Anime List Website',
=======
  title: 'Create Next App',
  description: 'Generated by create next app',
>>>>>>> af25d0a8041f5aae49e1453e07b82dd31a164558
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={inter.className} suppressHydrationWarning={true} >
        <Navbar />
        {children}
      </body>
=======
      <body className={inter.className}>{children}</body>
>>>>>>> af25d0a8041f5aae49e1453e07b82dd31a164558
    </html>
  )
}
